### ISSUE TITLE
Delete at -2 vote doesn't work

### ISSUE THREAD

**Issue by MrRedstoner** [xXAligatorXx/RepostCheckerBot#10]
The delete post at -2 votes feature seems to be broken, take a look:
[https://www.reddit.com/r/ProgrammerHumor/comments/brpnwx/pretty_sure_those_are_node_modules/eofk07p?utm_source=share&utm_medium=web2x](url)
Also might want to look at implementing something for more accurate detection

**Comment by A1igator** [comment]
Fixed the -2 vote not working
