### ISSUE TITLE
Make Code More Efficient for Reddit RepostCheckerBot!!!

### ISSUE THREAD

**Issue by A1igator** [xXAligatorXx/RepostCheckerBot#3]
Hello,

As I will be making the bot public and very easy to add into any subreddit, I require for it to be able to handle 1000s of posts a minute, and it is just not fast enough for that yet. I have exhausted my knowledge of efficiency in **Python, sqlite, and video and image hashing**.

I would very much appreciate it if you may help me make the code more efficient in any of those areas. I believe the sqlite implementation is the area that could be improved the most due to the amount of statements that I have.

Most of the slow parts of the code are in database.py . The set up has been explained in the readme. Please make a comment if you are interested or have any questions/problems or even if you believe the code is as efficient as it can be.  

Thanks for reading!

**Comment by chrisryancombs** [comment]
Hello!

My classmates (@irishes, @nip5, @mikeHartzell) and I would love to contribute to this project for a Hacktoberfest assignment.

**Comment by A1igator** [comment]
Right on! Fork the repository and go for it.

**Comment by chrisryancombs** [comment]
After giving a quick look, I noticed that new posts are inserted one at a time. This could be sped up a decent amount by instead using a multiple insert. The top two replies on this stackoverflow post give a little more insight: [link](https://stackoverflow.com/questions/1793169/which-is-faster-multiple-single-inserts-or-one-multiple-row-insert)

I'll start looking into how we would implement this.

**Comment by A1igator** [comment]
Sorry it took me this long, but that sounds like a good idea, especially for the initial start, as it gets 1000 of top, hot, and new posts of a subreddit.

**Comment by xXAligatorXx** [comment]
I changed a bit so you might want to pull

**Comment by chrisryancombs** [comment]
Just wanted to give a small update say that we're not dead :)

I threw together a python notebook to test out a few ideas with the insert speed update: [link](https://github.com/chrisryancombs/sqlite_insert_speed_test/blob/master/sql_insert_speed_test.ipynb)

It turns out that using string manip to create a big multiple insert is actually slower...
However, I did find that using sqlite's executemany method with a list of tuples is faster than single inserts and works much in the way I hoped a multiple insert would.

Please check out the notebook and let me know what you think.

**Comment by A1igator** [comment]
Nice progress! it appears the executemany method is our fastest option, so try to implement that.

**Comment by irishes** [comment]
Would you be interested in us adding documentation for this project?

**Comment by A1igator** [comment]
Sure if you think there is anything that needs documenting.

**Comment by irishes** [comment]
Would you like to test this off of one of our PR's or should we do it on our side? If so, do you have any instructions for testing?

**Comment by A1igator** [comment]
Set it up in a random subreddit that is dead or you have created. (I use r/fortnitebrm)., post an image, download the image from reddit (therefore some reddit compression is applied). Post the downloaded image. The bot should comment and report. You may also try running it in a big subreddit with the report/comment code commented out, to test how it handles inserting lots of posts. I'll test it out anyhow when you make the PR.

**Comment by A1igator** [comment]
Hey guys! How is it going?

**Comment by nip5** [comment]
Great! We just need to get everything put back together and we'll be ready to make the pull request and you can test it out on your end.

**Comment by chrisryancombs** [comment]
Looks like my three teammates have had a really hard time implementing the change over the last couple months. I will jump back into this and finish it up :)

**Comment by A1igator** [comment]
closing this for now, until you guys respond.
